### PR TITLE
First draft

### PR DESCRIPTION
**Pull request by kells1986**
@zviash here's a first draft. Let me know if there's anything I've missed.

@ivyas21 please can you check the steps work for you.

@drstarson @Loenike FYI

### CODE REVIEW

**Comment by ivyas21** [comment]
@kells1986 , 

I'm working on it.

**Comment by ivyas21** [comment]
@kells1986 , I don't see download model option on Mind's eye. It's not available on Production yet. I assume by Thursday it will be available.

**Comment by ivyas21** [comment]
@kells1986 , 

Step 3. Drag My-Passio-MindsEye-Model.mlmodel into the directory using finder. Make sure to replace the existing file. The dialog should like the one below. Click "Replace".  I don't need to replace model. Repo has `MyModel.mlmodel` . User/developer may get confused. 

Screen Shot 2023-05-02 at 2 18 43 PM

**Comment by ivyas21** [comment]
Once we correct the step 3 `MyModel.mlmodel`. That would fix Step 5.  because currently I don't see `My-Passio-MindsEye-Model.mlmodel` on left.

 
Screen Shot 2023-05-02 at 2 26 57 PM

@zviash , I think you need to change `MyModel.mlmodel` to `My-Passio-MindsEye-Model.mlmodel` in Passio-MindsEye-iOS-Distributions repo.

**Comment by ivyas21** [comment]
@zviash after your change. It all looks good. It works so smoothly. Thank you @kells1986  Doc/instructions are good.:rocket:

**Comment by kells1986** [comment]
Merging since @ivyas21 has tested

**Pull request merged**
